#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap		 2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config focus_follows_pointer true

bspc rule -a Firefox desktop='^1'
bspc rule -a vlc state=floating

xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh
setxkbmap -option grp:alt_shift_toggle us,ru &
$HOME/.fehbg
dunst &
